name: Run build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports
          retention-days: 5
